### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by avipars** [ZeANi-SHILIX/BabiBot#2]
היי, 

אשמח להוסיף תרגום של הדף הסבר ופקודות באנגלית. אפשר לעשות pull request? 
עדיף לבנות דף index-en.html לדוגמא ? או יש דרך יותר טובה?

**Comment by BabiApps** [comment]
האמת לא חשבתי על זה...
אני אבדוק מה כדאי לעשות ואני אחזיר לך תשובה

בכל מקרה הדף html כרגע לא מעודכן בכל הפקודות, אבל תודה על הנכונות לתרגם :)

**Comment by BabiApps** [comment]
היי, עשיתי שינויים בדף
אז כרגע מספיק לשנות רק את הקובץ כאן -
https://github.com/ZeANi-SHILIX/BabiBot/blob/main/commands.js
והרשימה תתעדכן גם בדף עצמו

אם תרצה תוכל להתחיל לתרגם, אבל לא מילאתי שם את כל הפקודות שיש כרגע בבוט...
אז אם באלך להוסיף גם כמה בעברית ;)

(וכמובן שאם יש הצעות לשיפור לשם הפקודה באנגלית וכדומה אני אשמח לקבל הצעות לתיקון)
תודה!

**Comment by avipars** [comment]
https://github.com/ZeANi-SHILIX/BabiBot/pull/3

כרגע זה תרגום של מה שיש בעברית
